### PR TITLE
Add EnvoyFilter and a test case for EnvoyFilter

### PR DESCRIPTION
**Pull request by sdake**

### CODE REVIEW

**Comment by nrjpoddar** [comment]
Thanks @sdake for the PR!

Few suggestions:
* If you can, please split Gopkg.* changes in 1 commit?
* Have another commit for code you wrote i.e. the wrapper structs
* Remaining commit for auto-generated code.

It's easier for me to review that way. Can you also clarify why are there so many changes in Gopkg.lock?

**Comment by sdake** [comment]
Will Do.

Cheers
-steve

**Comment by sdake** [comment]
@nrjpoddar Re Gopkg.lock changes I added a package (assert) by deleting Gopkg.lock - then dep update.  I'll attempt adding it the correct way.

Cheers
-steve

**Comment by nrjpoddar** [comment]
This is great! Thanks for the PR and addressing review comments. Cheers!

**Pull request merged**
